# ===============================
# APPLICATION CONFIG
# ===============================
spring.application.name=SchoolOS
server.port=8080
# ===============================
# DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/school_os?currentSchema=schoolos
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SQL SCRIPT EXECUTION
# ===============================
#spring.sql.init.mode=always
#spring.sql.init.schema-locations=classpath:schema.sql
#spring.sql.init.data-locations=classpath:data.sql

## ===============================
# CONNECTION POOL (Hikari)
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000

# ===============================
# LOGGING
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# =====================================================
# JWT CONFIGURATION
# =====================================================

jwt.secret=schoolos-secret-key-schoolos-secret-key-123456
jwt.expiration=86400000
